#!/bin/sh

CONFIGFILE=/etc/linuxmuster-chilli.conf

set -e

. /usr/share/debconf/confmodule

# load config if exists
if [ -e $CONFIGFILE ]; then
    . $CONFIGFILE || true

    # config to debconf
    if [ "$LDAP_SERVER" != "" ]; then
        db_set linuxmuster-chilli/ldap-server "$LDAP_SERVER"
    fi
    if [ "$BASEDN" != "" ]; then
        db_set linuxmuster-chilli/base-dn "$BASEDN"
    fi
    if [ "$LDAP_PASS" != "" ]; then
        db_set linuxmuster-chilli/ldap-pass "$LDAP_PASS"
    fi
    if [ "$HS_NETWORK" != "" ]; then
        db_set linuxmuster-chilli/hs-network "$HS_NETWORK"
    fi
    if [ "$HS_NETMASK" != "" ]; then
        db_set linuxmuster-chilli/hs-netmask "$HS_NETMASK"
    fi
    if [ "$HS_NAMESERVERS" != "" ]; then
        db_set linuxmuster-chilli/hs-nameservers "$HS_NAMESERVERS"
    fi
    if [ "$HS_LDAPGROUPS" != "" ]; then
        db_set linuxmuster-chilli/hs-ldapgroups "$HS_LDAPGROUPS"
    fi
    if [ "$LOGGING" != "" ]; then
        db_set linuxmuster-chilli/logging "$LOGGING"
    fi
    if [ "$HS_UAMALLOW" != "" ]; then
        db_set linuxmuster-chilli/hs-uamallow "$HS_UAMALLOW"
    fi
    if [ "$HS_HEADING" != "" ]; then
        db_set linuxmuster-chilli/hs-heading "$HS_HEADING"
    fi
fi

db_input high linuxmuster-chilli/ldap-server || true
db_input high linuxmuster-chilli/base-dn || true
db_input high linuxmuster-chilli/ldap-pass || true
db_input high linuxmuster-chilli/hs-network || true
db_input high linuxmuster-chilli/hs-netmask || true
db_input high linuxmuster-chilli/hs-nameservers || true
db_input high linuxmuster-chilli/hs-ldapgroups || true
db_input high linuxmuster-chilli/logging || true
db_input high linuxmuster-chilli/hs-uamallow || true
db_input high linuxmuster-chilli/hs-heading || true
db_go || true
