#!/bin/sh

CONFIGFILE=/etc/linuxmuster-chilli.conf

set -e

. /usr/share/debconf/confmodule

# load config if exists
if [ -e $CONFIGFILE ]; then
    . $CONFIGFILE || true

    # config to debconf
    db_set linuxmuster-chilli/ldap-server "$LDAP_SERVER"
    db_set linuxmuster-chilli/base-dn "$BASEDN"
    db_set linuxmuster-chilli/ldap-pass "$LDAP_PASS"
    db_set linuxmuster-chilli/hs-network "$HS_NETWORK"
    db_set linuxmuster-chilli/hs-netmask "$HS_NETMASK"
fi

db_input high linuxmuster-chilli/ldap-server || true
db_input high linuxmuster-chilli/base-dn || true
db_input high linuxmuster-chilli/ldap-pass || true
db_input high linuxmuster-chilli/hs-network || true
db_input high linuxmuster-chilli/hs-netmask || true
db_go || true
